# Generated by Django 3.2.16 on 2023-03-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('image', models.ImageField(default='images/users/defaultSellerImage.png', null=True,
                                            upload_to='images/sellers/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('image',
                 models.ImageField(default='images/users/defaultUserImage.png', null=True, upload_to='images/users/')),
            ],
        ),
    ]
